language: perl
perl:
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
before_install:
    - "cpanm Mojo::IOLoop"
    - "cpanm Test::More"
    - "cpanm Devel::Cover::Report::Coveralls"
script:
  perl Build.PL && ./Build && ./Build test && cover -test -report coveralls
