language: perl
matrix:
    fast_finish: true
perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - "cpanm -qn Mojolicious"
    - "cpanm -qn Test::More"
    - "cpanm -qn Test::Requires::Git"
    - "cpanm -qn Devel::Cover::Report::Codecov"
script:
  perl Makefile.PL && make test && cover -test -report codecov
